package comita.auto.selenium.applogic;

import comita.auto.selenium.model.FES_DELFM_DOC;

public class FES_DELFM_Helper extends DriverBasedHelper {
	
	public FES_DELFM_Helper(ApplicationManager manager) {
		super(manager.getWebDriver());
	}
	
	public void inputAllValuesDELFM(FES_DELFM_DOC fes) throws InterruptedException {		
		pages.fes_nko_Page.ensurePageLoaded()
			.setCorrespondentID(fes.getCorrespondentID())
			.selectTypeInfo(fes.getTypeInfo())
			.setDateOfFES(fes.getDateOfFES())
			.selectInfoAboutPersonType(fes.getInfoAboutPersonType())
			.setInfoAboutPersonSurname(fes.getInfoAboutPersonSurname())
			.setInfoAboutPersonName(fes.getInfoAboutPersonName())
			.setInfoAboutPersonPatronymic(fes.getInfoAboutPersonPatronymic())
			.setInfoAboutPersonINN(fes.getInfoAboutPersonINN())
			.setInfoAboutPersonLegalName(fes.getInfoAboutPersonLegalName())
			.setAuthorizedPosition(fes.getAuthorizedPosition())
			.setAuthorizedSurname(fes.getAuthorizedSurname())
			.setAuthorizedName(fes.getAuthorizedName())
			.setAuthorizedPatronymic(fes.getAuthorizedPatronymic())
			.setAuthorizedCodeAndPhone(fes.getAuthorizedCodeAndPhone())
			.setAuthorizedEmail(fes.getAuthorizedEmail())
			.selectinfoTabOfNKO()
			.selectRepresentativeTypeCode(fes.getNfoTypeCode())
			.selectRepresentativeType(fes.getNfoType())
			.setResidentSign(fes.getNfoResidentSign())
			.setNkoName(fes.getNfoName())
			.setNkoINN(fes.getNfoINN(), fes.getNfoINNIP())
			.setNkoKPP(fes.getNfoKPP())
			.setNkoOKPO(fes.getNfoOKPO())
			.selectNkoOKVED(fes.getNfoOKVED())
			.setNkoOGRN(fes.getNfoOGRN(), fes.getNfoOGRNIP())
			.selectIndustrySectorCode(fes.getNkoIndustrySectorCode())
			.setNkoPersonSurname(fes.getNfoPersonSurname())
			.setNkoPersonName(fes.getNfoPersonName())
			.setNkoPersonPatronymic(fes.getNfoPersonPatronymic())
			.selectNkoIdentityDocType(fes.getNfoIdentityDocType())
			.setNkoIdentityDocSerie(fes.getNfoIdentityDocSerie())
			.setNkoIdentityDocNumber(fes.getNfoIdentityDocNumber())
			.setNkoIdentityDocIssueDate(fes.getNfoIdentityDocIssueDate())
			.setNkoIdentityDocIssuer(fes.getNfoIdentityDocIssuer())
			.setNkoIdentityDocCodeDivision(fes.getNfoIdentityDocCodeDivision())
			.setNkoIdentityDocBirthDate(fes.getNfoIdentityDocBirthDate())
			.selectNkoBirthCountryCode(fes.getNfoBirthCountryCode())
			.selectNkoBirthSubjectCode(fes.getNfoBirthSubjectCode())
			.setNkoBirthArea(fes.getNfoBirthArea())
			.setNkoBirthCity(fes.getNfoBirthCity())
			.selectNkoAddressCountryCode(fes.getNfoAddressCountryCode())
			.selectNkoAddressSubjectCode(fes.getNfoAddressSubjectCode())
			.setNkoAddressArea(fes.getNfoAddressArea())
			.setNkoAddressCity(fes.getNfoAddressCity())
			.setNkoAddressStreet(fes.getNfoAddressStreet())
			.setNkoAddressHouse(fes.getNfoAddressHouse())
			.setNkoAddressCorp(fes.getNfoAddressCorp())
			.setNkoAddressApartment(fes.getNfoAddressApartment())
			.setPostalCode(fes.getPostalCode())
			.selectPostalCountryCode(fes.getPostalCountryCode())
			.selectPostalSubjectCode(fes.getPostalSubjectCode())
			.setPostalArea(fes.getPostalArea())
			.setPostalCity(fes.getPostalCity())
			.setPostalStreet(fes.getPostalStreet())
			.setPostalHouse(fes.getPostalHouse())
			.setPostalCorp(fes.getPostalCorp())
			.setPostalApartment(fes.getPostalApartment());
		pages.delfm_Page.ensurePageLoaded()
			.selectInfoAboutFESToDeleteTab()
			.setNumberFES(fes.getNumberFES())
			.setIdFES(fes.getIdFES())
			.setDateFES(fes.getDateFES())
			.setTypeFES(fes.getTypeFES())
			.setStatusFES(fes.getStatusFES())
			.setProvisionMethodFES(fes.getProvisionMethodFES())
			.setReasonsToDeleteFES(fes.getReasonsToDeleteFES());
	}
	
	public void inputRequiredValuesDELFM(FES_DELFM_DOC fes) throws InterruptedException {		
		pages.fes_nko_Page.ensurePageLoaded()
			.setCorrespondentID(fes.getCorrespondentID())
			.selectTypeInfo(fes.getTypeInfo())
			.setDateOfFES(fes.getDateOfFES())
			.selectInfoAboutPersonType(fes.getInfoAboutPersonType())
			.setInfoAboutPersonSurname(fes.getInfoAboutPersonSurname())
			.setInfoAboutPersonName(fes.getInfoAboutPersonName())
			.setInfoAboutPersonINN(fes.getInfoAboutPersonINN())
			.setInfoAboutPersonLegalName(fes.getInfoAboutPersonLegalName())
			.setAuthorizedPosition(fes.getAuthorizedPosition())
			.setAuthorizedSurname(fes.getAuthorizedSurname())
			.setAuthorizedName(fes.getAuthorizedName())
			.setAuthorizedCodeAndPhone(fes.getAuthorizedCodeAndPhone())
			.selectinfoTabOfNKO()
			.selectRepresentativeTypeCode(fes.getNfoTypeCode())
			.selectRepresentativeType(fes.getNfoType())
			.setResidentSign(fes.getNfoResidentSign())
			.setNkoName(fes.getNfoName())
			.setNkoINN(fes.getNfoINN(), fes.getNfoINNIP())
			.setNkoKPP(fes.getNfoKPP())
			.setNkoOKPO(fes.getNfoOKPO())
			.selectNkoOKVED(fes.getNfoOKVED())
			.setNkoOGRN(fes.getNfoOGRN(), fes.getNfoOGRNIP())
			.setNkoPersonSurname(fes.getNfoPersonSurname())
			.setNkoPersonName(fes.getNfoPersonName())
			.selectNkoIdentityDocType(fes.getNfoIdentityDocType())
			.setNkoIdentityDocIssueDate(fes.getNfoIdentityDocIssueDate())
			.setNkoIdentityDocIssuer(fes.getNfoIdentityDocIssuer())
			.selectNkoBirthCountryCode(fes.getNfoBirthCountryCode())
			.selectNkoBirthSubjectCode(fes.getNfoBirthSubjectCode())
			.setNkoBirthCity(fes.getNfoBirthCity())
			.selectNkoAddressCountryCode(fes.getNfoAddressCountryCode())
			.selectNkoAddressSubjectCode(fes.getNfoAddressSubjectCode())
			.setNkoAddressCity(fes.getNfoAddressCity())
			.setPostalCode(fes.getPostalCode())
			.selectPostalCountryCode(fes.getPostalCountryCode())
			.selectPostalSubjectCode(fes.getPostalSubjectCode())
			.setPostalCity(fes.getPostalCity());
		pages.delfm_Page.ensurePageLoaded()
			.selectInfoAboutFESToDeleteTab()
			.setNumberFES(fes.getNumberFES())
			.setIdFES(fes.getIdFES())
			.setDateFES(fes.getDateFES())
			.setTypeFES(fes.getTypeFES())
			.setStatusFES(fes.getStatusFES())
			.setProvisionMethodFES(fes.getProvisionMethodFES())
			.setReasonsToDeleteFES(fes.getReasonsToDeleteFES());
	}

}
