package comita.auto.selenium.applogic;

import comita.auto.selenium.model.FES_3FM_DOC;

public class FES_3FM_Helper extends DriverBasedHelper {
	
	public FES_3FM_Helper(ApplicationManager manager) {
		super(manager.getWebDriver());
	}
	
	public void inputAllValues3FM(FES_3FM_DOC fes) throws InterruptedException {		
		pages.fes_nko_Page.ensurePageLoaded()
			.setCorrespondentID(fes.getCorrespondentID())
			.selectTypeInfo(fes.getTypeInfo())
			.setDateOfFES(fes.getDateOfFES())
			.selectInfoAboutPersonType(fes.getInfoAboutPersonType())
			.setInfoAboutPersonSurname(fes.getInfoAboutPersonSurname())
			.setInfoAboutPersonName(fes.getInfoAboutPersonName())
			.setInfoAboutPersonPatronymic(fes.getInfoAboutPersonPatronymic())
			.setInfoAboutPersonINN(fes.getInfoAboutPersonINN())
			.setInfoAboutPersonLegalName(fes.getInfoAboutPersonLegalName())
			.setAuthorizedPosition(fes.getAuthorizedPosition())
			.setAuthorizedSurname(fes.getAuthorizedSurname())
			.setAuthorizedName(fes.getAuthorizedName())
			.setAuthorizedPatronymic(fes.getAuthorizedPatronymic())
			.setAuthorizedCodeAndPhone(fes.getAuthorizedCodeAndPhone())
			.setAuthorizedEmail(fes.getAuthorizedEmail())
			.selectinfoTabOfNKO()
			.selectRepresentativeTypeCode(fes.getNfoTypeCode())
			.selectRepresentativeType(fes.getNfoType())
			.setResidentSign(fes.getNfoResidentSign())
			.setNkoName(fes.getNfoName())
			.setNkoINN(fes.getNfoINN(), fes.getNfoINNIP())
			.setNkoKPP(fes.getNfoKPP())
			.setNkoOKPO(fes.getNfoOKPO())
			.selectNkoOKVED(fes.getNfoOKVED())
			.setNkoOGRN(fes.getNfoOGRN(), fes.getNfoOGRNIP())
			.selectIndustrySectorCode(fes.getNfoOKVED())
			.setNkoPersonSurname(fes.getNfoPersonSurname())
			.setNkoPersonName(fes.getNfoPersonName())
			.setNkoPersonPatronymic(fes.getNfoPersonPatronymic())
			.selectNkoIdentityDocType(fes.getNfoIdentityDocType())
			.setNkoIdentityDocSerie(fes.getNfoIdentityDocSerie())
			.setNkoIdentityDocNumber(fes.getNfoIdentityDocNumber())
			.setNkoIdentityDocIssueDate(fes.getNfoIdentityDocIssueDate())
			.setNkoIdentityDocIssuer(fes.getNfoIdentityDocIssuer())
			.setNkoIdentityDocCodeDivision(fes.getNfoIdentityDocCodeDivision())
			.setNkoIdentityDocBirthDate(fes.getNfoIdentityDocBirthDate())
			.selectNkoBirthCountryCode(fes.getNfoBirthCountryCode())
			.selectNkoBirthSubjectCode(fes.getNfoBirthSubjectCode())
			.setNkoBirthArea(fes.getNfoBirthArea())
			.setNkoBirthCity(fes.getNfoBirthCity())
			.selectNkoAddressCountryCode(fes.getNfoAddressCountryCode())
			.selectNkoAddressSubjectCode(fes.getNfoAddressSubjectCode())
			.setNkoAddressArea(fes.getNfoAddressArea())
			.setNkoAddressCity(fes.getNfoAddressCity())
			.setNkoAddressStreet(fes.getNfoAddressStreet())
			.setNkoAddressHouse(fes.getNfoAddressHouse())
			.setNkoAddressCorp(fes.getNfoAddressCorp())
			.setNkoAddressApartment(fes.getNfoAddressApartment())
			.setIPAddress(fes.getIpAddress());
		pages.fes_3fm_Page.ensurePageLoaded()
			.selectInfoAboutResultsOfInspectionTab()
			.selectRecordTypeFES(fes.getRecordTypeFES())
			.setDateOfChange(fes.getDateOfChange())
			.setDateOfPrevInspection(fes.getDateOfPrevInspection())
			.setStartOfPeriodDate(fes.getStartOfPeriodDate())
			.setEndOfPeriodDate(fes.getEndOfPeriodDate())
			.setStartOfInspectionDate(fes.getStartOfInspectionDate())
			.setEndOfInspectionDate(fes.getEndOfInspectionDate())
			.setTotalNumberOfCustomers(fes.getTotalNumberOfCustomers())
			.setNumberOfCustomersOrg(fes.getNumberOfCustomersOrg())
			.setNumberOfCustomersInd(fes.getNumberOfCustomersInd())
			.setTotalNumberOfBlocked(fes.getTotalNumberOfBlocked())
			.setNumberOfBlockedOrg(fes.getNumberOfBlockedOrg())
			.setNumberOfBlockedInd(fes.getNumberOfBlockedInd())
			.setTotalNumberOfFESForBlocked(fes.getTotalNumberOfFESForBlocked())
			.setTotalNumberOfNonBlocked(fes.getTotalNumberOfNonBlocked())
			.setNumberOfNonBlockedOrg(fes.getNumberOfNonBlockedOrg())
			.setNumberOfNonBlockedInd(fes.getNumberOfNonBlockedInd())
			.setNumberOfFESForNonBlocked(fes.getNumberOfFESForNonBlocked())
			.addRecord()
			.selectBaseApplyingMeasuresCode(fes.getBaseApplyingMeasuresCode())
			.setOrganizationCode(fes.getOrganizationCode())
			.setAdditionalInfo(fes.getAdditionalInfo())
			.clickOK();
	}
	
	public void inputRequiredValues3FM(FES_3FM_DOC fes) throws InterruptedException {		
		pages.fes_nko_Page.ensurePageLoaded()
			.setCorrespondentID(fes.getCorrespondentID())
			.selectTypeInfo(fes.getTypeInfo())
			.setDateOfFES(fes.getDateOfFES())
			.selectInfoAboutPersonType(fes.getInfoAboutPersonType())
			.setInfoAboutPersonSurname(fes.getInfoAboutPersonSurname())
			.setInfoAboutPersonName(fes.getInfoAboutPersonName())
			.setInfoAboutPersonINN(fes.getInfoAboutPersonINN())
			.setInfoAboutPersonLegalName(fes.getInfoAboutPersonLegalName())
			.setAuthorizedPosition(fes.getAuthorizedPosition())
			.setAuthorizedSurname(fes.getAuthorizedSurname())
			.setAuthorizedName(fes.getAuthorizedName())
			.setAuthorizedCodeAndPhone(fes.getAuthorizedCodeAndPhone())
			.selectinfoTabOfNKO()
			.selectRepresentativeTypeCode(fes.getNfoTypeCode())
			.selectRepresentativeType(fes.getNfoType())
			.setResidentSign(fes.getNfoResidentSign())
			.setNkoName(fes.getNfoName())
			.setNkoINN(fes.getNfoINN(), fes.getNfoINNIP())
			.setNkoKPP(fes.getNfoKPP())
			.setNkoOKPO(fes.getNfoOKPO())
			.selectNkoOKVED(fes.getNfoOKVED())
			.setNkoOGRN(fes.getNfoOGRN(), fes.getNfoOGRNIP())
			.setNkoPersonSurname(fes.getNfoPersonSurname())
			.setNkoPersonName(fes.getNfoPersonName())
			.selectNkoIdentityDocType(fes.getNfoIdentityDocType())
			.setNkoIdentityDocIssueDate(fes.getNfoIdentityDocIssueDate())
			.setNkoIdentityDocIssuer(fes.getNfoIdentityDocIssuer())
			.selectNkoBirthCountryCode(fes.getNfoBirthCountryCode())
			.selectNkoBirthSubjectCode(fes.getNfoBirthSubjectCode())
			.setNkoBirthCity(fes.getNfoBirthCity())
			.selectNkoAddressCountryCode(fes.getNfoAddressCountryCode())
			.selectNkoAddressSubjectCode(fes.getNfoAddressSubjectCode())
			.setNkoAddressCity(fes.getNfoAddressCity());
		pages.fes_3fm_Page.ensurePageLoaded()
			.selectInfoAboutResultsOfInspectionTab()
			.selectRecordTypeFES(fes.getRecordTypeFES())
			.setDateOfChange(fes.getDateOfChange())
			.setDateOfPrevInspection(fes.getDateOfPrevInspection())
			.setStartOfPeriodDate(fes.getStartOfPeriodDate())
			.setEndOfPeriodDate(fes.getEndOfPeriodDate())
			.setStartOfInspectionDate(fes.getStartOfInspectionDate())
			.setEndOfInspectionDate(fes.getEndOfInspectionDate())
			.setTotalNumberOfCustomers(fes.getTotalNumberOfCustomers())
			.setNumberOfCustomersOrg(fes.getNumberOfCustomersOrg())
			.setNumberOfCustomersInd(fes.getNumberOfCustomersInd())
			.setTotalNumberOfBlocked(fes.getTotalNumberOfBlocked())
			.setNumberOfBlockedOrg(fes.getNumberOfBlockedOrg())
			.setNumberOfBlockedInd(fes.getNumberOfBlockedInd())
			.setTotalNumberOfFESForBlocked(fes.getTotalNumberOfFESForBlocked())
			.setTotalNumberOfNonBlocked(fes.getTotalNumberOfNonBlocked())
			.setNumberOfNonBlockedOrg(fes.getNumberOfNonBlockedOrg())
			.setNumberOfNonBlockedInd(fes.getNumberOfNonBlockedInd())
			.setNumberOfFESForNonBlocked(fes.getNumberOfFESForNonBlocked())
			.addRecord()
			.selectBaseApplyingMeasuresCode(fes.getBaseApplyingMeasuresCode())
			.setOrganizationCode(fes.getOrganizationCode())
			.clickOK();
	}

}
