package comita.auto.selenium.applogic;

import comita.auto.selenium.model.FES_4FM_DOC;

public class FES_4FM_Helper extends DriverBasedHelper {
	
	public FES_4FM_Helper(ApplicationManager manager) {
		super(manager.getWebDriver());
	}
	
	public void inputAllValues4FM(FES_4FM_DOC fes) throws InterruptedException {		
		pages.fes_nko_Page.ensurePageLoaded()
			.setCorrespondentID(fes.getCorrespondentID())
			.selectTypeInfo(fes.getTypeInfo())
			.setDateOfFES(fes.getDateOfFES())
			.selectInfoAboutPersonType(fes.getInfoAboutPersonType())
			.setInfoAboutPersonSurname(fes.getInfoAboutPersonSurname())
			.setInfoAboutPersonName(fes.getInfoAboutPersonName())
			.setInfoAboutPersonPatronymic(fes.getInfoAboutPersonPatronymic())
			.setInfoAboutPersonINN(fes.getInfoAboutPersonINN())
			.setInfoAboutPersonLegalName(fes.getInfoAboutPersonLegalName())
			.setAuthorizedPosition(fes.getAuthorizedPosition())
			.setAuthorizedSurname(fes.getAuthorizedSurname())
			.setAuthorizedName(fes.getAuthorizedName())
			.setAuthorizedPatronymic(fes.getAuthorizedPatronymic())
			.setAuthorizedCodeAndPhone(fes.getAuthorizedCodeAndPhone())
			.setAuthorizedEmail(fes.getAuthorizedEmail())
			.selectinfoTabOfNKO()
			.selectRepresentativeTypeCode(fes.getNfoTypeCode())
			.selectRepresentativeType(fes.getNfoType())
			.setResidentSign(fes.getNfoResidentSign())
			.setNkoName(fes.getNfoName())
			.setNkoINN(fes.getNfoINN(), fes.getNfoINNIP())
			.setNkoKPP(fes.getNfoKPP())
			.setNkoOKPO(fes.getNfoOKPO())
			.selectNkoOKVED(fes.getNfoOKVED())
			.setNkoOGRN(fes.getNfoOGRN(), fes.getNfoOGRNIP())
			.selectIndustrySectorCode(fes.getNkoIndustrySectorCode())
			.setNkoPersonSurname(fes.getNfoPersonSurname())
			.setNkoPersonName(fes.getNfoPersonName())
			.setNkoPersonPatronymic(fes.getNfoPersonPatronymic())
			.selectNkoIdentityDocType(fes.getNfoIdentityDocType())
			.setNkoIdentityDocSerie(fes.getNfoIdentityDocSerie())
			.setNkoIdentityDocNumber(fes.getNfoIdentityDocNumber())
			.setNkoIdentityDocIssueDate(fes.getNfoIdentityDocIssueDate())
			.setNkoIdentityDocIssuer(fes.getNfoIdentityDocIssuer())
			.setNkoIdentityDocCodeDivision(fes.getNfoIdentityDocCodeDivision())
			.setNkoIdentityDocBirthDate(fes.getNfoIdentityDocBirthDate())
			.selectNkoBirthCountryCode(fes.getNfoBirthCountryCode())
			.selectNkoBirthSubjectCode(fes.getNfoBirthSubjectCode())
			.setNkoBirthArea(fes.getNfoBirthArea())
			.setNkoBirthCity(fes.getNfoBirthCity())
			.selectNkoAddressCountryCode(fes.getNfoAddressCountryCode())
			.selectNkoAddressSubjectCode(fes.getNfoAddressSubjectCode())
			.setNkoAddressArea(fes.getNfoAddressArea())
			.setNkoAddressCity(fes.getNfoAddressCity())
			.setNkoAddressStreet(fes.getNfoAddressStreet())
			.setNkoAddressHouse(fes.getNfoAddressHouse())
			.setNkoAddressCorp(fes.getNfoAddressCorp())
			.setNkoAddressApartment(fes.getNfoAddressApartment())
			.setIPAddress(fes.getIpAddress());
		pages.fes_4fm_Page.ensurePageLoaded()
			.selectInfoAboutFactsOfObstaclesTab()
			.addRecord()
			.selectRecordTypeFES(fes.getRecordTypeFES())
			.setCorrectionDate(fes.getCorrectionDate())
			.selectForeignCountryCode(fes.getForeignCountryCode())
			.setRequirementOfLegislation(fes.getRequirementOfLegislation())
			.setHandicappingForm(fes.getHandicappingForm())
			.setAdditionalInfo(fes.getAdditionalInfo())
			.clickOK();
	}
	
	public void inputRequiredValues4FM(FES_4FM_DOC fes) throws InterruptedException {		
		pages.fes_nko_Page.ensurePageLoaded()
			.setCorrespondentID(fes.getCorrespondentID())
			.selectTypeInfo(fes.getTypeInfo())
			.setDateOfFES(fes.getDateOfFES())
			.selectInfoAboutPersonType(fes.getInfoAboutPersonType())
			.setInfoAboutPersonSurname(fes.getInfoAboutPersonSurname())
			.setInfoAboutPersonName(fes.getInfoAboutPersonName())
			.setInfoAboutPersonINN(fes.getInfoAboutPersonINN())
			.setInfoAboutPersonLegalName(fes.getInfoAboutPersonLegalName())
			.setAuthorizedPosition(fes.getAuthorizedPosition())
			.setAuthorizedSurname(fes.getAuthorizedSurname())
			.setAuthorizedName(fes.getAuthorizedName())
			.setAuthorizedCodeAndPhone(fes.getAuthorizedCodeAndPhone())
			.selectinfoTabOfNKO()
			.selectRepresentativeTypeCode(fes.getNfoTypeCode())
			.selectRepresentativeType(fes.getNfoType())
			.setResidentSign(fes.getNfoResidentSign())
			.setNkoName(fes.getNfoName())
			.setNkoINN(fes.getNfoINN(), fes.getNfoINNIP())
			.setNkoKPP(fes.getNfoKPP())
			.setNkoOKPO(fes.getNfoOKPO())
			.selectNkoOKVED(fes.getNfoOKVED())
			.setNkoOGRN(fes.getNfoOGRN(), fes.getNfoOGRNIP())
			.setNkoPersonSurname(fes.getNfoPersonSurname())
			.setNkoPersonName(fes.getNfoPersonName())
			.selectNkoIdentityDocType(fes.getNfoIdentityDocType())
			.setNkoIdentityDocIssueDate(fes.getNfoIdentityDocIssueDate())
			.setNkoIdentityDocIssuer(fes.getNfoIdentityDocIssuer())
			.selectNkoBirthCountryCode(fes.getNfoBirthCountryCode())
			.selectNkoBirthSubjectCode(fes.getNfoBirthSubjectCode())
			.setNkoBirthCity(fes.getNfoBirthCity())
			.selectNkoAddressCountryCode(fes.getNfoAddressCountryCode())
			.selectNkoAddressSubjectCode(fes.getNfoAddressSubjectCode())
			.setNkoAddressCity(fes.getNfoAddressCity());
		pages.fes_4fm_Page.ensurePageLoaded()
			.selectInfoAboutFactsOfObstaclesTab()
			.addRecord()
			.selectRecordTypeFES(fes.getRecordTypeFES())
			.setCorrectionDate(fes.getCorrectionDate())
			.selectForeignCountryCode(fes.getForeignCountryCode())
			.setRequirementOfLegislation(fes.getRequirementOfLegislation())
			.setHandicappingForm(fes.getHandicappingForm())
			.clickOK();
	}

}
